name: Notify Discord

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Envoyer notification Discord
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        method: POST
        contentType: 'application/json'
        data: '{"content":"**[${{ github.repository }}]**\\nNouvelle modification !","embeds":[{"title":"Push réalisé sur ${{ github.ref }}","description":"Auteur : ${{ github.actor }}\\nDernier commit : `${{ github.event.head_commit.message }}`","url":"https://github.com/${{ github.repository }}/commit/${{ github.sha }}","color":5814783}]}'
